### PR TITLE
Purge examples

### PR DESCRIPTION
**Pull request by ReblochonMasque**
- Isolate broken examples in a legacy directory
- add a README guide to run the examples (addresses a pycharm issue, but there may be other help we would like to provide in the future)
- fix the `class Text` docstring that referenced legacy `drawing_tool`

Please let me know if that PR meets your expectations, and/or what you wish I change before merging.

I thought I could pull into a `dev` branch, but I did not find one, so this goes to `master`

### CODE REVIEW

**Comment by rvodden** [comment]
Hi!

Thank you so much for contributing to pysketcher, I really do appreciate it. Would you mind breaking your PR up into separate pieces for me please? Some of it can me merged immediately, but other parts I think need a little more thought.

1. I don't want to include `.idea` in this project's gitignore. The reason being that it is each contributors choice which editor or IDE they use and I don't want to maintain a list of all editor temporary files in our gitignore file. Instead you should configure your global gitignore so that these files are not included in all of your projects. [There is a good article on how to achieve this here](https://blog.martinhujer.cz/dont-put-idea-vscode-directories-to-projects-gitignore/)

1. I'm not sure how I feel about moving the broken examples into a new folder. Issue #1 tracks the solution to the examples issues, but I can see that making it clear which work and which don't could be helpful. If you could break this into a separate PR we can discuss on there. This might be the motivation I need to actually fix those examples, or maybe just delete them :-)

1. Your changes to the `Text` docstring are great, and can be merged immediately. Please do submit them on a clean PR.

1. I'm not sure what your list of removed examples achieves? These have not, in fact, been removes, but rather moves to the doctests of the appropriate classes. Again if this can be in a PR on its own we can discuss if it should be merged or not.

1. Now dimensions have been fixed, I'd rather fix vehicle_dim than move it into the legacy location.

1. I don't have to run like this in PyCharm, I can just run the file without the process which you have described in your readme amendment. (See attached picture). Can you open this as an issue and describe what you found without using your approach and we can see if we can resolve it? I'm not clear at the moment if its a pysketcher issue or an issue with your local pycharm setup - either way it would be good to get to the bottom of it.

Screenshot 2021-11-02 at 08 14 25

**Comment by rvodden** [comment]
There is a helpful suite of pre-commit hooks which will mean that anything you submit complies with the coding standards of the project. To use them run the following commands in your virtual environment of choice:

```
pip install pre-commit
pre-commit install
```

Then whenever you make a commit a short set of tests will run which validate that you comply with the coding style:

Screenshot 2021-11-02 at 08 38 09

**Comment by ReblochonMasque** [comment]
Thank you for your thorough reply, and your time giving me clear instructions on how to meet your expectations.

1 - ok, noted, thank you - I did not know you could use a global `.gitignore`; it is actually a great suggestion, and the article linked is quite clear!

2 - it is bad karma to have examples that don't work; this is why I segregated them. I will issue a new PR so you can decide what to do with it.

3 - ok, I will issue a PR for the docsctring in`class Text`.

4 -  Agreed, it achieves nothing more than a reminder. I think simple examples of individual shapes are useful, and I wanted to keep track of them for maybe reintroduce them later; however, if they were moved to the docs, this is fine, we don't need them or the reminder any longer.

5 - n/a

6 - You are running in the python console - my suggestion was to set the configurations such that a click on the green arrow would achieve precisely that.
I am using an ipython kernel, so my console is a bit different, and plots open in a floating window.
The idea was to save others the trouble of finding out what to do if the plot did not popup; it is indeed not a pysketcher issue, so maybe we don't have to care?

7 - This is great: I'll use pre-commit as per your instructions.

**Comment by rvodden** [comment]
I wasn't aware that broken examples are bad karma, but it certainly makes sense! Let's get them moved or fixed then! I look forward to your PR.

There were some issues with CI (a sphinx version conflict was causing the docs job to fail) which I have now fixed so you can trust the test reports from github  now!

Thanks once again for contributing :-)

**Comment by ReblochonMasque** [comment]
closing to re-issue with requested requirements

**Pull request closed without merging**
