### PR TITLE
Edit readme

### PR DESCRIPTION
**Pull request by ReblochonMasque**
Edit `README` to accurately reflect current situation.

### CODE REVIEW

**Comment by rvodden** [comment]
Can you explain your logic a little more please? I don't follow why you have made these suggestions? Perhaps in future you could open an issue and start a discussion before you raise a pull request?

In particular, the 0.1.0 release will mark our exit from the alpha phase. Why have you suggested we remove that commitment?

**Comment by ReblochonMasque** [comment]
Certainly:
It is better to warn people that the project is in alpha than to promise something you likely won't be able to hold to. (yes, I can explain why I am thinking that too)

There is nothing anywhere that mentions "solving capability"... but I am glad to hear you have that in mind. I've opened a discussion 5 days ago to asked you to provide clarifications about the scope.

**Comment by rvodden** [comment]
I'm very interested to understand why you don't think we can declare the API stable at 0.1.0. Please do elaborate.

>  I think there is room for a more flexible API that describes the properties of the various shapes and PySketcher will then be able to calculate where these shapes could appear.

[From the already open discussion](https://github.com/rvodden/pysketcher/discussions/286). Granted I don't use the phrase "solve", but "able to calculate where these shapes could appear".

**Comment by ReblochonMasque** [comment]
> rvodden force-pushed the edit_readme branch from 86ce51c to a1c646c 3 hours ago 

What is the reason for not merging the current PR instead?

**Pull request closed without merging**
